config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: {
    in: %w[chinese italian japanese french belgian],
    message: '%{value} is not a valid category'
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: {
    in: [0, 1, 2, 3, 4, 5],
    message: `%{value} is not a valid rating`
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content);
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1 class="mx-5 mt-3">Restaurant list</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <div class="card-product mt-3">
      <img src="https://media.cntraveler.com/photos/6411f8a3fb07ce6400b7dc5d/master/w_1920%2Cc_limit/Batea_MG_3395.JPG" />
      <div class="card-product-infos">
        <h2><%= link_to restaurant.name, restaurant_path(restaurant), class: "text-decoration-none text-dark"  %></h2>
        <p><%= restaurant.address %>  |  <%= restaurant.category  %></p>
      </div>
    </div>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
 <div class="container">
    <div class="restaurant-detail">
        <h1 class="restaurant-name"><%= @restaurant.name  %></h1>
        <p class="restaurant-address"><%= @restaurant.address  %></p>
        <p class="restaurant-rating"><strong>Category: <%= @restaurant.category.capitalize  %></strong></p>
    </div>
      <div class="reviews">
        <h2>Reviews</h2>
        <ul class="review-list">
          <% @restaurant.reviews.each do |review| %>
            <li class="review-item">
            <p class="review-content"><%= review.content  %></p>
            <span class="review-rating"><%= review.rating  %></span>
            </li>
          <% end %>
        </ul>
      </div>
      <%= link_to 'New Review', new_restaurant_review_path(@restaurant), class: 'btn btn-primary' %>
  </div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, label: "Content", placeholder: "Write your review here..." %>
  <%= f.input :rating, label: "Rating", collection: [0, 1, 2, 3, 4, 5], as: :select, prompt: "Choose a rating" %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>